### ISSUE TITLE
Take ownership: mgalang

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/wundertools-image-fuzzy-mariadb#3]
@mgalang can you please take ownership of this image.

This means:
- will be assigned on all Pull Requests
- will be responsible for testing any PR, to see if it breaks the build (locally or using quay.io automated builds)
- will be responsible for testing any PR, to see if the build image actually runs (less important)

To accept ownership, please comment here and close this issue.

**Comment by mgalang** [comment]
Challenge accepted
